# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default:
#            url: '%env(ELASTICSEARCH_URL)%'
            host: 192.168.33.15
            port: 9200
            transport: http
    indexes:
        town:
            settings:
                number_of_shards: 1
                analysis:
                    filter:
                        autocomplete_filter:
                                type: "edge_ngram"
                                min_gram: 1
                                max_gram: 10
                    analyzer:
                        autocomplete:
                            type: custom
                            tokenizer: lowercase
                            filter:
                                - autocomplete_filter

            finder: ~
            serializer:
                groups: [searchOut]
            persistence:
                elastica_to_model_transformer:
                    ignore_missing: true
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Town
                listener: ~
                provider: ~
            properties:
                nameUa:
                    type: text
                    analyzer: autocomplete
                nameObl: ~
                district: ~