vich_uploader:
    db_driver: orm
    mappings:
        user_ecp:
#            inject_on_load: true
#            delete_on_update: false
#            delete_on_remove: true
            upload_destination: '%kernel.project_dir%/assets/docs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            uri_prefix: '/account'
    metadata:
        auto_detection: true
#        cache: file
#        type: attribute
