framework:
    workflows:
        application_flow:
            type: 'state_machine' # or 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\DevelopmentApplication
            initial_marking: draft
            places:
                - draft
                - numbered
                - rejected
                - published
            transitions:
                to_number:
                    guard: "is_granted('ROLE_USER')"
                    from: draft
                    to:   numbered
                publish:
                    from: numbered
                    to:   published
                reject:
                    from: numbered
                    to:   rejected
                reopen:
                    from: rejected
                    to: draft
        drawn_area_flow:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\DrawnArea
            initial_marking: created
            places:
                - created
                - published
                - archived
            transitions:
                to_publish:
                    from: created
                    to: published
                to_archive:
                    from: published
                    to: archived